version: '2'

services:
  app:
    image: 'denispronin/airline-project:1.0.7'
    build:
      context: .
      dockerfile: Dockerfile_Project
    container_name: app
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/airline_db
  app-payment:
    image: 'denispronin/airline-payments:1.0.7'
    build:
      context: .
      dockerfile: Dockerfile_Payments
    container_name: app-payment
    ports:
      - "8081:8081"
  db:
    image: 'postgres:12.12'
    container_name: db
    environment:
      - POSTGRES_DB=airline_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root