FROM maven:3.6.0-jdk-11-slim AS build

WORKDIR /build/common
COPY common/pom.xml .
COPY common/src /build/src
RUN mvn -f /build/common/pom.xml clean install

WORKDIR /build
COPY airline-payments/pom.xml .
COPY airline-payments/src /build/src
RUN mvn -f /build/pom.xml clean package

FROM adoptopenjdk:11-jre-hotspot
COPY --from=build /build/target/airline-payments.jar airline-payments.jar
EXPOSE 8080
ENTRYPOINT ["java", "-Xmx512m", "-Xms256m", "-jar", "airline-payments.jar"]