-- liquibase formatted sql

-- changeset alex_evdokimov:1668600479276-1
CREATE TABLE admin
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT "adminPK" PRIMARY KEY (id)
);

-- changeset alex_evdokimov:1668600479276-2
CREATE TABLE aircrafts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aircraft_number VARCHAR(15)                             NOT NULL,
    model           VARCHAR(255)                            NOT NULL,
    model_year      INTEGER                                 NOT NULL,
    flight_range    INTEGER                                 NOT NULL,
    CONSTRAINT "aircraftsPK" PRIMARY KEY (id)
);

-- changeset alex_evdokimov:1668600479276-3
CREATE TABLE airline_manager
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT "airline_managerPK" PRIMARY KEY (id)
);

-- changeset alex_evdokimov:1668600479276-4
CREATE TABLE category
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_type VARCHAR(255)                            NOT NULL,
    CONSTRAINT "categoryPK" PRIMARY KEY (id)
);

-- changeset alex_evdokimov:1668600479276-5
CREATE TABLE destination
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    airport_code VARCHAR(255)                            NOT NULL,
    airport_name VARCHAR(15)                             NOT NULL,
    city_name    VARCHAR(15),
    country_name VARCHAR(30)                             NOT NULL,
    timezone     VARCHAR(255)                            NOT NULL,
    CONSTRAINT "destinationPK" PRIMARY KEY (id)
);

-- changeset alex_evdokimov:1668600479276-6
CREATE TABLE flights
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code           VARCHAR(255)                            NOT NULL,
    flight_status  VARCHAR(255),
    arrival_date   TIMESTAMP WITHOUT TIME ZONE,
    departure_date TIMESTAMP WITHOUT TIME ZONE,
    aircraft_id    BIGINT,
    from_id        BIGINT,
    to_id          BIGINT,
    CONSTRAINT "flightsPK" PRIMARY KEY (id)
);

-- changeset alex_evdokimov:1668600479276-7
CREATE TABLE flight_seats
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fare          INTEGER,
    is_registered BOOLEAN                                 NOT NULL,
    is_sold       BOOLEAN                                 NOT NULL,
    flight_id     BIGINT                                  NOT NULL,
    seat_id       BIGINT                                  NOT NULL,
    CONSTRAINT "flight_seatsPK" PRIMARY KEY (id)
);

-- changeset alex_evdokimov:1668600479276-8
CREATE TABLE passengers
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email                    VARCHAR(255)                            NOT NULL,
    first_name               VARCHAR(128),
    last_name                VARCHAR(128),
    middle_name              VARCHAR(128),
    birth_date               date,
    gender                   VARCHAR(255),
    phone_number             VARCHAR(64),
    serial_number_passport   VARCHAR(255),
    passport_issuing_country VARCHAR(255),
    passport_issuing_date    date,
    password                 VARCHAR(255)                            NOT NULL,
    CONSTRAINT "passengersPK" PRIMARY KEY (id)
);

-- changeset alex_evdokimov:1668600479276-9
CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT "rolesPK" PRIMARY KEY (id)
);

-- changeset alex_evdokimov:1668600479276-10
CREATE TABLE route
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    departure_date       date                                    NOT NULL,
    number_of_passengers INTEGER                                 NOT NULL,
    destination_from_id  BIGINT                                  NOT NULL,
    destination_to_id    BIGINT                                  NOT NULL,
    CONSTRAINT "routePK" PRIMARY KEY (id)
);

-- changeset alex_evdokimov:1668600479276-11
CREATE TABLE seats
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    seat_number            VARCHAR(5)                              NOT NULL,
    is_near_emergency_exit BOOLEAN                                 NOT NULL,
    is_locked_back         BOOLEAN                                 NOT NULL,
    category_id            BIGINT,
    aircraft_id            BIGINT,
    CONSTRAINT "seatsPK" PRIMARY KEY (id)
);

-- changeset alex_evdokimov:1668600479276-12
CREATE TABLE tickets
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_number  VARCHAR(255)                            NOT NULL,
    flight_id      BIGINT                                  NOT NULL,
    passenger_id   BIGINT,
    flight_seat_id BIGINT                                  NOT NULL,
    CONSTRAINT "ticketsPK" PRIMARY KEY (id)
);

-- changeset alex_evdokimov:1668600479276-13
CREATE TABLE user_roles
(
    users_id BIGINT NOT NULL,
    roles_id BIGINT NOT NULL,
    CONSTRAINT "user_rolesPK" PRIMARY KEY (users_id, roles_id)
);

-- changeset alex_evdokimov:1668600479276-14
ALTER TABLE admin
    ADD CONSTRAINT UC_ADMINEMAIL_COL UNIQUE (email);

-- changeset alex_evdokimov:1668600479276-15
ALTER TABLE aircrafts
    ADD CONSTRAINT UC_AIRCRAFTSAIRCRAFT_NUMBER_COL UNIQUE (aircraft_number);

-- changeset alex_evdokimov:1668600479276-16
ALTER TABLE airline_manager
    ADD CONSTRAINT UC_AIRLINE_MANAGEREMAIL_COL UNIQUE (email);

-- changeset alex_evdokimov:1668600479276-17
ALTER TABLE category
    ADD CONSTRAINT UC_CATEGORYCATEGORY_TYPE_COL UNIQUE (category_type);

-- changeset alex_evdokimov:1668600479276-18
ALTER TABLE destination
    ADD CONSTRAINT UC_DISTINATIONAIRPORT_CODE_COL UNIQUE (airport_code);

-- changeset alex_evdokimov:1668600479276-19
ALTER TABLE passengers
    ADD CONSTRAINT UC_PASSENGERSEMAIL_COL UNIQUE (email);

-- changeset alex_evdokimov:1668600479276-20
ALTER TABLE flights
    ADD CONSTRAINT UC_FLIGHTSCODE_COL UNIQUE (code);

-- changeset alex_evdokimov:1668600479276-21
ALTER TABLE passengers
    ADD CONSTRAINT UC_PASSENGERSSERIAL_NUMBER_PASSPORT_COL UNIQUE (serial_number_passport);

-- changeset alex_evdokimov:1668600479276-22
ALTER TABLE tickets
    ADD CONSTRAINT UC_TICKETTICKET_NUMBER_COL UNIQUE (ticket_number);

-- changeset alex_evdokimov:1668600479276-23
ALTER TABLE seats
    ADD CONSTRAINT "FK7x57fav15snw7rt24op82ibig" FOREIGN KEY (aircraft_id) REFERENCES aircrafts (id);

-- changeset alex_evdokimov:1668600479276-24
ALTER TABLE flight_seats
    ADD CONSTRAINT "FKiphse4lu86qb9bep0rwn8rqce" FOREIGN KEY (flight_id) REFERENCES flights (id);

-- changeset alex_evdokimov:1668600479276-25
ALTER TABLE flights
    ADD CONSTRAINT "FK6j6d37r18yyr3ybv0ktcjrw6h" FOREIGN KEY (to_id) REFERENCES destination (id);

-- changeset alex_evdokimov:1668600479276-26
ALTER TABLE flight_seats
    ADD CONSTRAINT "FK94wbpjrnpj549y623sur7glx7" FOREIGN KEY (seat_id) REFERENCES seats (id);

-- changeset alex_evdokimov:1668600479276-27
ALTER TABLE user_roles
    ADD CONSTRAINT "FKdbv8tdyltxa1qjmfnj9oboxse" FOREIGN KEY (roles_id) REFERENCES roles (id);

-- changeset alex_evdokimov:1668600479276-28
ALTER TABLE route
    ADD CONSTRAINT "FKee3xli8uq1awgay4sc6x17vts" FOREIGN KEY (destination_to_id) REFERENCES destination (id);

-- changeset alex_evdokimov:1668600479276-29
ALTER TABLE flights
    ADD CONSTRAINT "FKo9jvf5gvgbrhgl3nh2obanw6u" FOREIGN KEY (aircraft_id) REFERENCES aircrafts (id);

-- changeset alex_evdokimov:1668600479276-30
ALTER TABLE flights
    ADD CONSTRAINT "FKqdm52g52hse8kslnf6payv5ck" FOREIGN KEY (from_id) REFERENCES destination (id);

-- changeset alex_evdokimov:1668600479276-31
ALTER TABLE route
    ADD CONSTRAINT "FKrvyi2alt0bsesp8rhcm1fe7tp" FOREIGN KEY (destination_from_id) REFERENCES destination (id);

-- changeset alex_evdokimov:1668600479276-32
ALTER TABLE seats
    ADD CONSTRAINT "FK1oruplc50q6p77e469q1ulaeb" FOREIGN KEY (category_id) REFERENCES category (id);

-- changeset alex_evdokimov:1668600479276-33
ALTER TABLE tickets
    ADD CONSTRAINT "FK1ds262xq345nkvs5o9ptnftwr" FOREIGN KEY (passenger_id) REFERENCES passengers (id);

-- changeset alex_evdokimov:1668600479276-34
ALTER TABLE tickets
    ADD CONSTRAINT "FKtdayegtd891qq5xm0axfbckvy" FOREIGN KEY (flight_id) REFERENCES flights (id);

-- changeset alex_evdokimov:1668600479276-35
ALTER TABLE tickets
    ADD CONSTRAINT "FKgdhx9g4egduse9gi9cm8nejwi" FOREIGN KEY (flight_seat_id) REFERENCES flight_seats (id);

-- changeset alex_evdokimov:1668600479276-36
CREATE SEQUENCE seq_aircraft START 1000 INCREMENT 1

-- changeset alex_evdokimov:1668600479276-37
CREATE SEQUENCE seq_seat START 1000 INCREMENT 1

-- changeset alex_evdokimov:1668600479276-38
CREATE SEQUENCE seq_role START 1000 INCREMENT 1

-- changeset alex_evdokimov:1668600479276-39
CREATE SEQUENCE seq_user START 1000 INCREMENT 1

-- changeset alex_evdokimov:1668600479276-40
CREATE SEQUENCE seq_category START 1000 INCREMENT 1

-- changeset alex_evdokimov:1668600479276-41
CREATE SEQUENCE seq_destination START 1000 INCREMENT 1

-- changeset alex_evdokimov:1668600479276-42
CREATE SEQUENCE seq_flights START 1000 INCREMENT 1

-- changeset alex_evdokimov:1668600479276-43
CREATE SEQUENCE seq_flight_seats START 1000 INCREMENT 1

-- changeset alex_evdokimov:1668600479276-44
CREATE SEQUENCE seq_route START 1000 INCREMENT 1

-- changeset alex_evdokimov:1668600479276-45
CREATE SEQUENCE seq_tickets START 1000 INCREMENT 1