apiVersion: v1
kind: ConfigMap
metadata:
  name: airline-config-map
data:
  application.yml: |
    spring:
      liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
      application:
        name: app
      profiles:
        active: dev
      datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://db-service:5432/postgres
        username: root
        password: root
        hikari:
          leak-detection-threshold: 60000
          maximum-pool-size: 20
          cloud:
            openfeign:
              client:
                config:
                  default:
                    connectTimeout: 5000
                    readTimeout: 5000
                    loggerLevel: basic
      jpa:
        show-sql: false
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            storage_engine: innodb
            current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
            format_sql: true
            jdbc:
              time_zone: Europe/Moscow
            cache:
              use_second_level_cache: true
              region:
                factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
              ehcache:
                missing_cache_strategy: create
      mail:
        host: smtp.yandex.ru
        port: 465
        username: XXXX
        password: XXXX

        protocol: smtps
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher

    jwt:
      secret:
        access: QZnCUVCnP3aukiTOa8XxPkfHODqpXB9xkg/o72yhIh4GE3BPiZszU4fYjJZTbcUcyGM/Bb5N81rv9Csq7blwCA==
        refresh: 7OTNSWG1vNDf0tgRcVBAFIq6nUlA4QajZUCqn2hpQs1oVKg1qjxB9l9Ik8NltL2QIM6HJYZg8V6zyHJgP0BHEg==
      refreshExpiration:
        accessTokeMin: 1440
        refreshTokeDays: 15

    mail:
      debug: true

    notification:
      periodOfDbCheck:
        milliseconds: 10000
      beforeDeparture:
        seconds: 86400

    logging:
      config: classpath:log4j2-prod.yaml

    app:
      feign:
        config:
          name: Payments
          url: http://airline-payments-service:8081