-- changeset dmitry_kosterin:1.13.1.1
CREATE TABLE timezones
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country_name VARCHAR(30)                             NOT NULL,
    city_name    VARCHAR(30)                             NOT NULL,
    gmt          VARCHAR(9)                              NOT NULL,
    gmt_winter   VARCHAR(9)                              NOT NULL,
    CONSTRAINT "timezonesPK" PRIMARY KEY (id)
);
