CREATE TABLE payments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_state   VARCHAR(255) NOT NULL,
    CONSTRAINT "paymentsPK" PRIMARY KEY (id)
);

CREATE SEQUENCE seq_payment START 1000 INCREMENT 1;


CREATE TABLE payments_bookings_id
(
    payments_id     BIGINT,
    index           INT,
    bookings_id     BIGINT
);