-- changeset olga-alikulieva:1.15.1

DROP TABLE IF EXISTS admin CASCADE;
DROP TABLE IF EXISTS airline_manager CASCADE;
DROP TABLE IF EXISTS passengers CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;

