CREATE TABLE searches
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_id              BIGINT,
    to_id                BIGINT,
    return_date          date,
    departure_date       date NOT NULL,
    number_of_passengers INTEGER NOT NULL,
    CONSTRAINT "searchesPK" PRIMARY KEY (id)
);

ALTER TABLE searches
    ADD CONSTRAINT "FK1es2ks4yv25n78jlh6vfeiadc" FOREIGN KEY (from_id) REFERENCES destination (id);

ALTER TABLE searches
    ADD CONSTRAINT "FKmr4214480arwkx4h595d1bia6" FOREIGN KEY (to_id) REFERENCES destination (id);